### ISSUE TITLE
VSCodium not allowed?

### ISSUE THREAD

**Issue by ylluminate** [harrison-broadbent/railsnotes-ruby-on-rails-extension-pack#1]
Is there a reason that this extension pack is not being allowed to be installed on VSCodium 1.85.2?

The following is the result of such an attempt when one follows [these instructions](https://github.com/VSCodium/vscodium/blob/master/docs/index.md#user-content-howto-switch-marketplace) to facilitate this:

> Can't install 'railsnotes.railsnotes-ruby-on-rails-extension-pack' extension because it is not compatible with the current version of VSCodium (version 1.85.2).

**Comment by harrison-broadbent** [comment]
Hey! It's actually just because I specified `"vscode": "^1.86.0"` as the min version for this extension pack.

That's because one of the extensions has specified that version in _their_ extension. I've opened an issue on that extensions repo — https://github.com/aliariff/vscode-erb-beautify/issues/59 — and I'm hoping they'll drop the min version. Then I can lower the min version for this pack. 

To solve this, maybe you can update VS Codium?

**Comment by ylluminate** [comment]
It's one of my family members who is learning Ruby/Rails and I was/am helping them. It appears they installed it via Homebrew and there are no updates beyond `1.85.2.24019` yet for it. They were, however, able to manage to install *each* of the plugins separately from your plugin links you gave... including the erb one you note... which seems quite odd. Hmm.

**Comment by harrison-broadbent** [comment]
@ylluminate hey! Just letting you know that I've just released `v1.1.0` of this extension pack which drops the minimum required version to `1.80.0`, in line with the adjustments made by the `vscode-erb-beautify` extension. 

It _should_ now work just fine for your family member. Let me know if it continues to be an issue!
Going to close this now but please re-open it if this problem continues.
